package provision

import (
	"fmt"

	"github.com/nimsforest/mycelium/pkg/mycelium"
)

// ForestConfig generates the forest.yaml content for an organization.
func ForestConfig(org *mycelium.Organization, leafNodeHubURL string) string {
	return fmt.Sprintf(`# Forest config for organization: %s
# Auto-generated by mycelium provision

sources: {}
trees: {}
treehouses: {}
nims: {}
songbirds: {}
`, org.Name)
}

// ForestSystemdUnit generates the systemd unit file for a forest instance.
func ForestSystemdUnit(slug string) string {
	return fmt.Sprintf(`[Unit]
Description=NimsForest - %s
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/forest run --config /etc/nimsforest/%s/forest.yaml
Restart=on-failure
RestartSec=5
Environment=FOREST_CONFIG=/etc/nimsforest/%s/forest.yaml
Environment=JETSTREAM_DIR=/var/lib/nimsforest/%s/jetstream

[Install]
WantedBy=multi-user.target
`, slug, slug, slug, slug)
}

// LandSystemdUnit generates the systemd unit file for a land instance.
func LandSystemdUnit(slug string, port int) string {
	return fmt.Sprintf(`[Unit]
Description=Land - %s
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/land serve --config /etc/land/%s/land.yaml --listen :%d
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`, slug, slug, port)
}

// NodeInfoJSON generates the node-info.json content.
func NodeInfoJSON(slug string) string {
	return fmt.Sprintf(`{
  "forest_id": "%s",
  "node_id": "%s-node-1"
}
`, slug, slug)
}
